### ISSUE TITLE
`Flarum` start discussion button color glitch/rainbow `css` style

### ISSUE THREAD

**Issue by andatoshiki** [white-windmills/lostark-forum#6]
```css
.IndexPage-newDiscussion {
    background: linear-gradient(124deg, #ff2400, #e81d1d, #e8b71d, #e3e81d, #1de840, #1ddde8, #2b1de8, #dd00f3, #dd00f3);
    color: #fff;
    background-size: 1800% 1800%;
    -webkit-animation: rainbow 15s ease infinite;
    -z-animation: rainbow 15s ease infinite;
    -o-animation: rainbow 15s ease infinite;
    animation: rainbow 15s ease infinite;
}

@-webkit-keyframes rainbow {
    0% {
        background-position: 0% 82%
    }

    50% {
        background-position: 100% 19%
    }

    100% {
        background-position: 0% 82%
    }
}

@-moz-keyframes rainbow {
    0% {
        background-position: 0% 82%
    }

    50% {
        background-position: 100% 19%
    }

    100% {
        background-position: 0% 82%
    }
}

@-o-keyframes rainbow {
    0% {
        background-position: 0% 82%
    }

    50% {
        background-position: 100% 19%
    }

    100% {
        background-position: 0% 82%
    }
}

@keyframes rainbow {
    0% {
        background-position: 0% 82%
    }

    50% {
        background-position: 100% 19%
    }

    100% {
        background-position: 0% 82%
    }
}
```
**Result**:
![image](https://user-images.githubusercontent.com/101481353/163896666-6e38ab16-9b5a-4c56-b5de-fc03ad1d1ebb.png)
